export const INFO_TS_FILE_NAME = 'info'
export const INFO_YAML_FILE_NAME = 'info.yaml'
export const TRANSCRIPT_FILE_NAME = 'transcript.srt'
export const OUTLINE_FILE_NAME = 'outline.txt'
export const COVER_ART_FILE_NAME = 'cover-art.png'
